sonar.projectKey=ecom-saas-backend
sonar.projectName=eCom SaaS Backend

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

# Coverage produced by jest (lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclude generated / non-product code from analysis + coverage
sonar.exclusions=src/migrations/**,src/seeders/**,coverage/**,node_modules/**,infra/**
sonar.coverage.exclusions=src/migrations/**,src/seeders/**,tests/**,src/server.js,src/instrumentation.js,src/config/**

sonar.sourceEncoding=UTF-8
