{
 "title": "eCom SaaS API",
 "tags": [
  "ecom",
  "sit753"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "App Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"ecom-app\"}",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(ecom_http_request_duration_seconds_count[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(ecom_http_request_duration_seconds_count{status_code=~\"5..\"}[5m])) / sum(rate(ecom_http_request_duration_seconds_count[5m]))",
     "legendFormat": "error ratio"
    }
   ]
  },
  {
   "title": "Latency p50 / p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(ecom_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ecom_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Process Memory (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ecom_process_resident_memory_bytes",
     "legendFormat": "rss"
    }
   ]
  }
 ]
}